export { default as Home } from './Home'
export { default as Search } from './Search'
export { default as SynonymList } from './SynonymList'
export { default as Quotes } from './Quotes'
export { default as Popup } from './PopupContainer'
export { default as ErrorPage } from './ErrorPage'
